name: 'dbt_acb'
version: '1.0.0'

profile: 'dbt_acb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_acb:
    staging:
      +materialized: table

vars:
  landing_data_dir: "../data/landing"