name: 'acb_analytics'
version: '1.0.0'

profile: 'dbt_acb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  acb_analytics:
    staging:
      +schema: staging

    intermediate:
      +schema: intermediate

    marts:
      +schema: marts

seeds:
  acb_analytics:
    +schema: reference 
    court_zones: {}
    play_types: {}

vars:
  landing_data_dir: "../data/landing"