{{ config(
    materialized='table',
    schema='marts',
    tags=['acb_analytics']
) }}

with agg as (
	select
		edition_id,
		competition_id,
		competition_phase,
		team_id,
		count(1) as games,
		sum(seconds) as seconds,
		sum(points) as points,
		sum(opponent_points) as opponent_points,
		sum(free_throws_made) as free_throws_made,
		sum(free_throws_attempted) as free_throws_attempted,
		sum(two_pointers_made) as two_pointers_made,
		sum(two_pointers_attempted) as two_pointers_attempted,
		sum(three_pointers_made) as three_pointers_made,
		sum(three_pointers_attempted) as three_pointers_attempted,
		sum(field_goals_made) as field_goals_made,
		sum(field_goals_attempted) as field_goals_attempted,
		sum(dunks) as dunks,
		sum(assists) as assists,
		sum(off_rebounds) as off_rebounds,
		sum(def_rebounds) as def_rebounds,
		sum(total_rebounds) as total_rebounds,
		sum(steals) as steals,
		sum(turnovers) as turnovers,
		sum(blocks) as blocks,
		sum(received_blocks) as received_blocks,
		sum(personal_fouls) as personal_fouls,
		sum(fouls_drawn) as fouls_drawn,
		sum(rating) as rating,
        sum(offensive_possessions) as offensive_possessions,
        sum(defensive_possessions) as defensive_possessions,
        sum(possessions) as possessions
	from {{ ref('fact_team_games') }}
	group by edition_id, competition_id, competition_phase, team_id
)
select 
	edition_id,
    competition_id,
    competition_phase,
    team_id,
	games,
    seconds,
	points,
	opponent_points,
	free_throws_made,
	free_throws_attempted,
	free_throws_made / NULLIF(free_throws_attempted, 0) AS free_throws_pct,
	two_pointers_made,
	two_pointers_attempted,
	two_pointers_made / NULLIF(two_pointers_attempted, 0) AS two_pointers_pct,
	three_pointers_made,
	three_pointers_attempted,
	three_pointers_made / NULLIF(three_pointers_attempted, 0) AS three_pointers_pct,
	field_goals_made,
	field_goals_attempted,
	(two_pointers_made + three_pointers_made) / NULLIF(two_pointers_attempted + three_pointers_attempted, 0) AS field_goals_pct,
	(two_pointers_made + 1.5 * three_pointers_made) / NULLIF(two_pointers_attempted + three_pointers_attempted, 0) AS effective_field_goals_pct,
	points / NULLIF(2 * (two_pointers_attempted + three_pointers_attempted + 0.44 * free_throws_attempted), 0) AS true_shooting_pct,
	dunks,
	assists,
	off_rebounds,
	def_rebounds,
	total_rebounds,
	steals,
	turnovers,
	blocks,
	received_blocks,
	personal_fouls,
	fouls_drawn,
	rating,
	offensive_possessions,
	defensive_possessions,
    possessions,
    100.0 * points / NULLIF(offensive_possessions, 0) as offensive_rating,
    100.0 * opponent_points / NULLIF(defensive_possessions, 0) as defensive_rating,
    100.0 * (points / NULLIF(offensive_possessions, 0) - opponent_points / NULLIF(defensive_possessions, 0)) as net_rating
from agg