{{ config(
    materialized='view',
    schema='marts',
    tags=['acb_analytics']
) }}

SELECT
    edition_id,
    competition_id,
    competition_phase,
    player_id,
    team_id,
    player_game_role,
    games,
    games_started,
    seconds / 60.0 AS minutes,
    points / games AS points_per_game,
    free_throws_made / games AS free_throws_made_per_game,
    free_throws_attempted / games AS free_throws_attempted_per_game,
    free_throws_made / NULLIF(free_throws_attempted, 0) AS free_throws_pct,
    two_pointers_made / games AS two_pointers_made_per_game,
    two_pointers_attempted / games AS two_pointers_attemped_per_game,
	two_pointers_made / NULLIF(two_pointers_attempted, 0) AS two_pointers_pct,
    three_pointers_made / games AS three_pointers_made_per_game,
    three_pointers_attempted / games AS three_pointers_attemped_per_game,
    three_pointers_made / NULLIF(three_pointers_attempted, 0) AS three_pointers_pct,
    field_goals_made / games AS field_goals_made_per_game,
    field_goals_attempted / games AS field_goals_attempted_per_game,    
    (two_pointers_made + three_pointers_made) / NULLIF(two_pointers_attempted + three_pointers_attempted, 0) AS field_goals_pct,
	(two_pointers_made + 1.5 * three_pointers_made) / NULLIF(two_pointers_attempted + three_pointers_attempted, 0) AS effective_field_goals_pct,
	points / NULLIF(2 * (two_pointers_attempted + three_pointers_attempted + 0.44 * free_throws_attempted), 0) AS true_shooting_pct,
    dunks / games AS dunks_per_game,
    assists / games AS assists_per_game,
    off_rebounds / games AS off_rebounds_per_game,
    def_rebounds / games AS def_rebounds_per_game,
    total_rebounds / games AS total_rebounds_per_game,
    steals / games AS steals_per_game,
    turnovers / games AS turnovers_per_game,
    blocks / games AS blocks_per_game,
    received_blocks / games AS received_blocks_per_game,
    personal_fouls / games AS personal_fouls_per_game,
    fouls_drawn / games AS fouls_drawn_per_game,
    plus_minus / games AS plus_minus_per_game,
    rating / games AS rating_per_game
FROM {{ ref('agg_player_totals') }}